### ISSUE TITLE
Case error on some attributes

### ISSUE THREAD

**Issue by MCMic** [tiredofit/fusiondirectory-plugin-kopano#1]
In the code, `KopanoEnabledFeatures` and `KopanoDisabledFeatures` should be `kopanoEnabledFeatures` and `kopanoDisabledFeatures` to match the case used in the schema.

**Comment by tiredofit** [comment]
Hi Come, thanks for reviewing, this is embarrassing that it was only a 1 byte issue on both. Indeed it is now working. I appreciate your time for helping out.
